### ISSUE TITLE
Allow user to select bill with a number less than 4 digits

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#115]
The autosuggest sorts by reverse order (it seems) and there is no way for a user to just hit return to select the bill that they want (e.g. `116hr300`).

![image](https://user-images.githubusercontent.com/217356/103108276-3bf5bb80-45fb-11eb-8e89-74c9734b731e.png)

For this issue: 
- [ ] Sort the autosuggest from lower to higher numbers (or at least fewer digits)
- [ ] Allow user to hit return to select the currently typed value, even if it is not selected from the dropdown.

**Comment by aih** [comment]
I've tried this out in `issue/autocomplete` and it works. However, I'm now getting this error:

```
[28/Dec/2020 23:15:37] "GET /bills/116hr100 HTTP/1.1" 200 44131
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 62942)
Traceback (most recent call last):
  File "/Users/arihershowitz/.pyenv/versions/3.7.4/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/arihershowitz/.pyenv/versions/3.7.4/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/arihershowitz/.pyenv/versions/3.7.4/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/arihershowitz/.pyenv/versions/flatgov/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 174, in handle
    self.handle_one_request()
  File "/Users/arihershowitz/.pyenv/versions/flatgov/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/Users/arihershowitz/.pyenv/versions/3.7.4/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer
----------------------------------------
```

**Comment by aih** [comment]
I don't know what was happening. It's working now:
![image](https://user-images.githubusercontent.com/217356/103300275-5b9e3280-49b3-11eb-99df-fcefea2f3c0e.png)
