### ISSUE TITLE
Skip adding text when there is no summary (adding cosponsors)

### ISSUE THREAD

**Issue by aih** [aih/FlatGov#55]
Running `python manage.py related_bills`, I get this error:

```
Adding sponsor info
116hjres58 - bill has updated.
Cosponsors are added to bill - 116hjres58.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/arihershowitz/.pyenv/versions/flatgov/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/arihershowitz/.pyenv/versions/flatgov/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/arihershowitz/.pyenv/versions/flatgov/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/arihershowitz/.pyenv/versions/flatgov/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/arihershowitz/Documents/workspace/FlatGovDir/FlatGov/server_py/flatgov/common/management/commands/related_bills.py", line 14, in handle
    makeAndSaveRelatedBills()
  File "/Users/arihershowitz/Documents/workspace/FlatGovDir/FlatGov/server_py/flatgov/common/relatedBills.py", line 171, in makeAndSaveRelatedBills
    addSponsors()
  File "/Users/arihershowitz/Documents/workspace/FlatGovDir/FlatGov/server_py/flatgov/common/relatedBills.py", line 109, in addSponsors
    summary = billData.get('summary', {}).get('text')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by kapphire** [comment]
Fixed
